product:
    pattern:  /
    #defaults: { _controller: "BitcoinAdminBundle:Product:index" }
    defaults: { _controller: "BitcoinAdminBundle:Product:list" }

product_show:
    pattern:  /{id}/show
    defaults: { _controller: "BitcoinAdminBundle:Product:show" }

product_new:
    pattern:  /new
    defaults: { _controller: "BitcoinAdminBundle:Product:new" }

product_create:
    pattern:  /create
    defaults: { _controller: "BitcoinAdminBundle:Product:create" }
    requirements: { _method: post }

product_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BitcoinAdminBundle:Product:edit" }

product_update:
    pattern:  /{id}/update
    defaults: { _controller: "BitcoinAdminBundle:Product:update" }
    requirements: { _method: post|put }

product_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BitcoinAdminBundle:Product:delete" }
    requirements: { _method: post|delete|get }

product_grid:
    pattern:  /grid
    defaults: { _controller: "BitcoinAdminBundle:Product:getProduct" }
    
product_list:
    pattern:  /list
    defaults: { _controller: "BitcoinAdminBundle:Product:list" }
    
product_add:
    pattern:  /add
    defaults: { _controller: "BitcoinAdminBundle:Product:add" }