<?php

namespace Proxies\__CG__\Bitcoin\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \Bitcoin\AdminBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'productTitle', 'description', 'price', 'priceListed', 'createdDate', 'modifiedDate', 'featured', 'fkProductCat', 'sku', 'images', 'reviews');
        }

        return array('__isInitialized__', 'id', 'productTitle', 'description', 'price', 'priceListed', 'createdDate', 'modifiedDate', 'featured', 'fkProductCat', 'sku', 'images', 'reviews');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setProductTitle($productTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductTitle', array($productTitle));

        return parent::setProductTitle($productTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductTitle', array());

        return parent::getProductTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', array());

        return parent::setCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', array());

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedDate', array());

        return parent::setModifiedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedDate', array());

        return parent::getModifiedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkProductCat(\Bitcoin\AdminBundle\Entity\ProductCategory $fkProductCat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkProductCat', array($fkProductCat));

        return parent::setFkProductCat($fkProductCat);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkProductCat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkProductCat', array());

        return parent::getFkProductCat();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFeatured()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeatured', array());

        return parent::getFeatured();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeatured($featured)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeatured', array($featured));

        return parent::setFeatured($featured);
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceListed($priceListed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceListed', array($priceListed));

        return parent::setPriceListed($priceListed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceListed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceListed', array());

        return parent::getPriceListed();
    }

    /**
     * {@inheritDoc}
     */
    public function setSku($sku)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSku', array($sku));

        return parent::setSku($sku);
    }

    /**
     * {@inheritDoc}
     */
    public function getSku()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSku', array());

        return parent::getSku();
    }

    /**
     * {@inheritDoc}
     */
    public function setImages($images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImages', array($images));

        return parent::setImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function addImages(\Bitcoin\AdminBundle\Entity\ProductImages $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImages', array($images));

        return parent::addImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImages(\Bitcoin\AdminBundle\Entity\ProductImages $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImages', array($images));

        return parent::removeImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', array());

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\Bitcoin\AdminBundle\Entity\ProductImages $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', array($images));

        return parent::addImage($images);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\Bitcoin\AdminBundle\Entity\ProductImages $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', array($images));

        return parent::removeImage($images);
    }

    /**
     * {@inheritDoc}
     */
    public function addPhoto(\Bitcoin\AdminBundle\Entity\ProductImages $photos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhoto', array($photos));

        return parent::addPhoto($photos);
    }

    /**
     * {@inheritDoc}
     */
    public function removePhoto(\Bitcoin\AdminBundle\Entity\ProductImages $photos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePhoto', array($photos));

        return parent::removePhoto($photos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotos', array());

        return parent::getPhotos();
    }

    /**
     * {@inheritDoc}
     */
    public function getReviews()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviews', array());

        return parent::getReviews();
    }

    /**
     * {@inheritDoc}
     */
    public function addReview(\Bitcoin\AdminBundle\Entity\ProductReview $reviews)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReview', array($reviews));

        return parent::addReview($reviews);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReview(\Bitcoin\AdminBundle\Entity\ProductReview $reviews)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReview', array($reviews));

        return parent::removeReview($reviews);
    }

}
