bitcoin_site:
    resource: "@BitcoinSiteBundle/Resources/config/routing.yml"
    prefix:   /

bitcoin_admin:
    resource: "@BitcoinAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

oneup_uploader:
    resource: .
    type: uploader