bitcoin_site:
    resource: "@BitcoinSiteBundle/Resources/config/routing.yml"
    prefix:   /

bitcoin_admin:
    resource: "@BitcoinAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb