bitcoin_admin_homepage:
    pattern:  /
    defaults: { _controller: BitcoinAdminBundle:Admin:index }

bitcoin_admin_login:
    pattern:  /login
    defaults: { _controller: BitcoinAdminBundle:Login:login }
    
bitacoin_admin_logout:
    pattern:  /logout
    defaults: { _controller: BitcoinAdminBundle:Admin:logout }
    
BitcoinAdminBundle_productcategory:
    resource: "@BitcoinAdminBundle/Resources/config/routing/productcategory.yml"
    prefix:   /product-category

BitcoinAdminBundle_product:
    resource: "@BitcoinAdminBundle/Resources/config/routing/product.yml"
    prefix:   /product

BitcoinAdminBundle_productimage:
    resource: "@BitcoinAdminBundle/Resources/config/routing/productimage.yml"
    prefix:   /product-image

productcategory_test:
    pattern:  /test
    defaults: { _controller: "BitcoinAdminBundle:Test:index" }
    
productcategory_testwe:
    pattern:  /test/test
    defaults: { _controller: "BitcoinAdminBundle:Test:test" }