parameters:
#    bitcoin_admin.example.class: Bitcoin\AdminBundle\Example

services:
#    bitcoin_admin.example:
#        class: %bitcoin_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    bitcoin.twig.bitcoin_extension:
        class: Bitcoin\AdminBundle\Twig\Extension\ValidationExtension
        tags:
            - { name: twig.extension }
#    acme_hello.upload_listene:
#        class: Bitcoin\AdminBundle\EventListener\UploadListener
#        tags:
#            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }