bitcoin_site_homepage:
    pattern:  /
    defaults: { _controller: BitcoinSiteBundle:Index:index}

bitcoin_product:
    pattern:  /prduct-detail/{id}/{prdoductTitle}
    defaults: { _controller: BitcoinSiteBundle:Index:productDetail}

bitcoin_product_review:
    pattern:  /prduct-review/{id}
    defaults: { _controller: BitcoinSiteBundle:Secure:submitReview}

BitcoinSiteBundle_user:
    resource: "@BitcoinSiteBundle/Resources/config/routing/user.yml"
    prefix:   /account
    
BitcoinSiteBundle_cart:
    resource: "@BitcoinSiteBundle/Resources/config/routing/cart.yml"
    prefix:   /cart