bitcoin_site_homepage:
    pattern:  /
    defaults: { _controller: BitcoinSiteBundle:Index:index}

bitcoin_product:
    pattern:  /prduct-detail/{id}/{prdoductTitle}
    defaults: { _controller: BitcoinSiteBundle:Index:productDetail}