parameters:
#    bitcoin_site.example.class: Bitcoin\SiteBundle\Example

services:
    bitcoin.twig.custom_extension:
        class: Bitcoin\SiteBundle\Twig\Extension\CustomExtension
        tags:
            - { name: twig.extension }